export const SET_USER_SESSION = 'SET_USER_SESSION';
export const LOG_USER_OUT = 'LOG_USER_OUT';
export const LOG_USER_IN = 'LOG_USER_IN';
export const SET_MESSAGES = 'SET_MESSAGES';
export const SAVE_USER = 'SAVE_USER';
export const SIGN_USER_UP = 'SIGN_USER_UP';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CREATE_CHATROOM = 'CREATE_CHATROOM';
// export const IS_LOADING = 'IS_LOADING';